inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: '2.3'

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "fusuma.gemspec"

Layout/LineLength:
  Max: 100
  Exclude:
    - "fusuma.gemspec"
    - "**/*_spec.rb"

# For rubocop < 1.0.0
Style/HashEachMethods:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformKeys:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformValues:
  Enabled: true

# For compatible ruby 2.3
Style/RedundantBegin:
  Enabled: false

Lint/RaiseException:
   Enabled: true
Lint/StructNewOverride:
   Enabled: true
